### ISSUE TITLE
repair_segment table grows and grows -- what are your clean up mechanisms that you have in place ?

### ISSUE THREAD

**Issue by djsly** [spotify/cassandra-reaper#110]
```
reaper_db=> select count(*) from repair_segment;
count
--------
142081
(1 row)
```

I was wondering what you guys use to prevent the postgres DB from growing indefinitely. 

From what I can see, the segments for runs that completed successfully don't really need to stay in the DB ? 

Thanks!

**Comment by varjoranta** [comment]
There is no automated clean up mechanism currently, but when deleting the runs using the REST DELETE endpoints, the segments will get deleted as well.

**Comment by djsly** [comment]
I have added a PR https://github.com/spotify/cassandra-reaper/pull/119 for this automated feature.
