### ISSUE TITLE
Add CLI commands for removing schedules, clusters, and old runs

### ISSUE THREAD

**Issue by varjoranta** [spotify/cassandra-reaper#55]
The Reaper will get cluttered rather fast with all the old runs, schedulings, and clusters. It is not possible currently to clean up the Reaper, unless one connects directly to the database and deletes rows from there manually.

**Comment by varjoranta** [comment]
HTTP endpoints have been added, but CLI tool must be updated still... soon.

**Comment by rzvoncek** [comment]
Now we have #72 merged, can this be closed?

**Comment by varjoranta** [comment]
There is already a GUI that supports the DELETE requests, and we will not add these into the CLI tool yet.
