### ISSUE TITLE
Add support for jmx authentication on cassandra cluster

### ISSUE THREAD

**Issue by n0rad** [spotify/cassandra-reaper#60]

**Comment by varjoranta** [comment]
@n0rad does the pure username / password authentication serve your needs, or were you thinking about something more complex like LDAP auth?

**Comment by n0rad** [comment]
I just need the username/password since JMX on my cassandra cluster has authentication with jmxremote.password file.

**Comment by varjoranta** [comment]
So I guess e696db46b674bdf71d2b1c96200422edf05e0232 solves it for you?

**Comment by n0rad** [comment]
looking at the code, it should be ok
