### ISSUE TITLE
Repairs timeout with error state in case of nothing to repair

### ISSUE THREAD

**Issue by spodkowinski** [spotify/cassandra-reaper#64]
The source code seems to ignore return value 0 from triggerRepair in JmxProxy. This value indicate a "nothing to repair" scenario. However, its handled as a regular commandId by SegmentRunner. Eventually the task will end up in an error state after a timeout. 

I've tried to fix this issue with the following code. However, tests will still fail due to a wrong repair state and I can't really figure out whats why.

```java
        commandId = coordinator.triggerRepair(segment.getStartToken(), segment.getEndToken(),
                                              keyspace, repairRun.getRepairParallelism(),
                                              repairUnit.getColumnFamilies());
        
        if(commandId == 0) {
          LOG.info("Nothing to repair for keyspace {}", keyspace);
          context.storage.updateRepairSegment(segment.with()
                  .coordinatorHost(coordinator.getHost())
                  .state(RepairSegment.State.DONE)
                  .build(segmentId));
          segmentRunners.remove(segment.getId());
          return;
        }
```

**Comment by Bj0rnen** [comment]
Hi, I've applied your change plus an accompanying change in RepairRunner.intensityBasedDelayMillis. Check if this fixes your issue.

**Comment by spodkowinski** [comment]
Looks good, the repair job will now finish with DONE state in case nothing had to be repaired. Quickly tested with a new 2.0 cluster bootstrapped with CCM.
