### ISSUE TITLE
Add reasons for RepairRun ending in ERROR in lastEvent field

### ISSUE THREAD

**Issue by Bj0rnen** [spotify/cassandra-reaper#78]
When you see that a repair run ended in ERROR, it's never clear why that happened. You have to dig in the logs to try to figure out the cause. The lastEvent field in RepairRun provides no helpful information when an error has occured. The reason for failure should be stored there.It could be a stack trace or something more short and to the point.

**Comment by rzvoncek** [comment]
After merging #90, can we close this?
